name: Auto add issue to projects

on:
  workflow_call:

jobs:
  add-issue-to-projects:
    name: Add issue to projects
    runs-on: ubuntu-latest
    steps:
      - name: label/qurbani
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'labeled' &&
          contains(github.event.issue.labels.*.name, 'campaign/qurbani')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/14'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
      - name: team/ahmadn3o
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'ahmadn3o')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/12'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/aminjafer-n3o
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'aminjafer-n3o')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/10'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/CarolineRoose
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'CarolineRoose')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/25'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/CloP11
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'CloP11')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/13'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
      - name: team/nadrummond
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'nadrummond')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/2'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/NawalElMakni
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'NawalElMakni')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/24'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/rn3o
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'rn3o')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/9'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/sirajurrahmann
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'sirajurrahmann')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/8'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: team/talhamalik4025
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'talhamalik4025')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/11'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
