name: 'auto-add-issue-to-project'

on:
  workflow_call:

jobs:
  add-issue-to-project:
    name: Add Issue to user Project
    runs-on: ubuntu-latest
    steps:
      - name: Add to team/noor-drummond
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.action == 'assigned' &&
          contains(github.event.issue.assignees.*.login, 'nadrummond')
        with:
          project-url: 'https://github.com/orgs/muslimhands/projects/2'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
